services:
  shop:
    build:
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: mysql:8.3
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shops
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    command: --port 3306

volumes:
  db_data: